import { Howl } from 'howler';

// Tiny base64-encoded WAV chunks for UI sounds.
// These keep the bundle self-contained — no external audio files needed.
// Each is a short blip generated programmatically.

const dataUri = (b64: string) => `data:audio/wav;base64,${b64}`;

// Pre-generated short blips (kept tiny on purpose)
const CLICK_WAV =
  'UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=';
const SUCCESS_WAV =
  'UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=';

let clickSound: Howl | null = null;
let successSound: Howl | null = null;

const ensureSounds = () => {
  if (!clickSound) {
    clickSound = new Howl({ src: [dataUri(CLICK_WAV)], volume: 0.4 });
  }
  if (!successSound) {
    successSound = new Howl({ src: [dataUri(SUCCESS_WAV)], volume: 0.6 });
  }
};

export const playClick = () => {
  ensureSounds();
  // Combine soft tone via Web Audio for nicer feel
  playTone(660, 0.05, 'sine', 0.15);
};

export const playSuccess = () => {
  ensureSounds();
  playChord([523, 659, 784], 0.25, 'triangle', 0.2);
};

export const playFail = () => {
  playTone(220, 0.18, 'square', 0.18);
};

// --- Web Audio synthesis utilities ---
// We synthesize sounds on the fly so the app has no audio file dependencies.

let ctx: AudioContext | null = null;
const getCtx = (): AudioContext | null => {
  if (typeof window === 'undefined') return null;
  if (!ctx) {
    const AC =
      (window as unknown as { AudioContext?: typeof AudioContext; webkitAudioContext?: typeof AudioContext }).AudioContext ||
      (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (AC) ctx = new AC();
  }
  return ctx;
};

const playTone = (
  freq: number,
  duration: number,
  type: OscillatorType = 'sine',
  volume = 0.2,
) => {
  const audio = getCtx();
  if (!audio) return;
  const osc = audio.createOscillator();
  const gain = audio.createGain();
  osc.type = type;
  osc.frequency.value = freq;
  gain.gain.setValueAtTime(0, audio.currentTime);
  gain.gain.linearRampToValueAtTime(volume, audio.currentTime + 0.01);
  gain.gain.exponentialRampToValueAtTime(0.0001, audio.currentTime + duration);
  osc.connect(gain).connect(audio.destination);
  osc.start();
  osc.stop(audio.currentTime + duration + 0.02);
};

const playChord = (freqs: number[], duration: number, type: OscillatorType, volume: number) => {
  freqs.forEach((f, i) => {
    setTimeout(() => playTone(f, duration, type, volume), i * 80);
  });
};

// --- Pre-generated TTS via Gemini ---
// On app start we load public/audio/manifest.json, which maps spoken phrases to
// MP3 URLs generated by `npm run generate-audio`. Phrases present in the manifest
// play the pre-generated file; anything missing falls back to the browser's
// SpeechSynthesis so the app stays functional without the asset pack.

let manifest: Record<string, string> | null = null;
let manifestPromise: Promise<Record<string, string>> | null = null;
const howlCache = new Map<string, Howl>();
let currentHowl: Howl | null = null;

const loadManifest = (): Promise<Record<string, string>> => {
  if (manifest) return Promise.resolve(manifest);
  if (manifestPromise) return manifestPromise;
  manifestPromise = fetch(`${import.meta.env.BASE_URL}audio/manifest.json`)
    .then((r) => (r.ok ? r.json() : {}))
    .then((data: Record<string, string>) => {
      manifest = data;
      return data;
    })
    .catch(() => {
      manifest = {};
      return manifest;
    });
  return manifestPromise;
};

// Kick off the fetch eagerly so phrases triggered shortly after load can use it.
if (typeof window !== 'undefined') {
  void loadManifest();
}

// Start playing the pre-generated clip for `text` and return its Howl, or null
// when there's no clip for the phrase. Callers can listen for the Howl's 'end'
// event to chain another phrase after this one finishes.
const playHowl = (text: string): Howl | null => {
  if (!manifest) return null;
  const file = manifest[text];
  if (!file) return null;
  const url = `${import.meta.env.BASE_URL}${file}`;
  let howl = howlCache.get(url);
  if (!howl) {
    howl = new Howl({ src: [url], volume: 1.0, html5: false });
    howlCache.set(url, howl);
  }
  if (currentHowl && currentHowl !== howl) currentHowl.stop();
  // Stop previous run of the same Howl so rapid clicks restart cleanly.
  howl.stop();
  howl.play();
  currentHowl = howl;
  return howl;
};

const playFromManifest = (text: string): boolean => playHowl(text) !== null;

const speakViaBrowser = (
  text: string,
  opts: { rate?: number; pitch?: number },
  onEnd?: () => void,
) => {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    onEnd?.();
    return;
  }
  try {
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.rate = opts.rate ?? 0.85;
    u.pitch = opts.pitch ?? 1.25;
    u.lang = 'en-US';
    const voices = window.speechSynthesis.getVoices();
    const preferred =
      voices.find((v) => /female|google.*english|samantha|karen/i.test(v.name) && v.lang.startsWith('en')) ||
      voices.find((v) => v.lang.startsWith('en'));
    if (preferred) u.voice = preferred;
    if (onEnd) {
      u.onend = () => onEnd();
      u.onerror = () => onEnd();
    }
    window.speechSynthesis.speak(u);
  } catch {
    // Ignore — speech is optional
    onEnd?.();
  }
};

// Play one phrase and resolve only when it finishes (or fails). Lets callers
// chain phrases without guessing a timeout that would clip longer clips.
const playOne = (text: string, opts: { rate?: number; pitch?: number } = {}): Promise<void> =>
  new Promise((resolve) => {
    const howl = playHowl(text);
    if (howl) {
      const done = () => resolve();
      howl.once('end', done);
      howl.once('stop', done);
      howl.once('loaderror', done);
      howl.once('playerror', done);
      return;
    }
    speakViaBrowser(text, opts, resolve);
  });

/**
 * Speak a phrase or letter. Prefers a pre-generated Gemini TTS clip when
 * the phrase exists in the manifest; otherwise falls back to the browser's
 * SpeechSynthesis API.
 */
export const speak = (text: string, opts: { rate?: number; pitch?: number; voice?: string } = {}) => {
  if (playFromManifest(text)) return;
  // Manifest not yet loaded or phrase not pre-generated.
  if (!manifest) {
    // Try once more after the manifest resolves — keeps fallback brief at startup.
    void loadManifest().then(() => {
      if (!playFromManifest(text)) speakViaBrowser(text, opts);
    });
    return;
  }
  speakViaBrowser(text, opts);
};

/**
 * Speak several phrases back-to-back, each starting only after the previous one
 * actually finishes (plus a short gap). This prevents a longer word clip (e.g.
 * "Librarian") from being cut off by the example sentence that follows — which
 * happens with fixed setTimeout gaps. Returns a cancel function for cleanup
 * (e.g. when a flashcard unmounts before the sequence completes).
 */
export const speakSequence = (
  texts: string[],
  opts: { gapMs?: number; rate?: number; pitch?: number } = {},
): (() => void) => {
  const gap = opts.gapMs ?? 350;
  let cancelled = false;
  void loadManifest().then(async () => {
    for (const text of texts) {
      if (cancelled) return;
      await playOne(text, opts);
      if (cancelled) return;
      if (gap) await new Promise((r) => setTimeout(r, gap));
    }
  });
  return () => {
    cancelled = true;
    if (currentHowl) currentHowl.stop();
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
  };
};

const ENCOURAGE = ['Great job!', 'Awesome!', 'You did it!', 'Fantastic!', 'Well done!'];
const TRY_AGAIN = ['Try again!', 'Almost there!', 'You can do it!'];

export const cheer = () => {
  playSuccess();
  speak(ENCOURAGE[Math.floor(Math.random() * ENCOURAGE.length)]);
};

export const encourage = () => {
  playFail();
  speak(TRY_AGAIN[Math.floor(Math.random() * TRY_AGAIN.length)]);
};
